security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        doctrine:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: doctrine
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /logout
                target: /
            remember_me:
                secret: $XCm0Z6LHB5vexrFqwhc
                lifetime: 604800
                path: /
                always_remember_me: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/edit_trick, roles: ROLE_USER }
        - { path: ^/delete_trick, roles: ROLE_USER }
        - { path: ^/add_trick, roles: ROLE_USER }
        - { path: ^/post, roles: ROLE_USER }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/manage_image, roles: ROLE_USER }
        - { path: ^/manage_video, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
