security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        doctrine:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: doctrine
            form_login:
                login_path: login
                check_path: login

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http, host: snowtricks*$ }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https, host: ^xtrazyx\.fr$ }
        - { path: ^/edit_trick, roles: ROLE_USER, requires_channel: https, host: ^xtrazyx\.fr$ }
        - { path: ^/delete_trick, roles: ROLE_USER, requires_channel: https, host: ^xtrazyx\.fr$ }
        - { path: ^/add_trick, roles: ROLE_USER, requires_channel: https, host: ^xtrazyx\.fr$ }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https, host: ^xtrazyx\.fr$ }
