swiftmailer:
    transport:    '%env(MAILER_TRAN)%'
    auth_mode:    '%env(MAILER_AUTH)%'
    host:         '%env(MAILER_HOST)%'
    encryption:   '%env(MAILER_ENCR)%'
    port:         '%env(MAILER_PORT)%'
    username:     '%env(MAILER_USER)%'
    password:     '%env(MAILER_PASS)%'
